PREFIX BMRBo: <http://bmrbpub.protein.osaka-u.ac.jp/schema/mmcif_nmr-star.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entry_id ?entity_id ?entity_name ?uniprot_id
FROM <http://bmrbpub.protein.osaka-u.ac.jp/rdf/bmr>
WHERE {

  ?s_up BMRBo:entity_db_link.entry_id ?entry_id ;
        BMRBo:entity_db_link.entity_id ?entity_id ;
        BMRBo:entity_db_link.database_code "SP" ; # uniprot
        BMRBo:entity_db_link.accession_code ?uniprot_id ;
        rdfs:seeAlso ?s_uniprot .

  ?s_en BMRBo:entity.entry_id ?entry_id ;
        BMRBo:entity.id ?entity_id ;
        BMRBo:entity.name ?entity_name .

} ORDER BY ?entry_id
