PREFIX BMRBo: <http://bmrbpub.pdbj.org/schema/mmcif_nmr-star.owl#>

SELECT ?entity_id ?sequence
FROM <http://bmrbpub.pdbj.org/rdf/bmr>
WHERE {

  ?s_up BMRBo:entity.entry_id ?entry_id ; # fill entry_id.
        BMRBo:entity.id ?entity_id ;
        BMRBo:entity.polymer_seq_one_letter_code ?sequence .

}
