PREFIX BMRBo: <http://bmrbpub.pdbj.org/schema/mmcif_nmr-star.owl#>

SELECT ?entry_id ?seq_id ?comp_id ?ca_ppm
FROM <http://bmrbpub.pdbj.org/rdf/bmr>
WHERE {

  ?s_ca BMRBo:atom_chem_shift.atom_id "CA" ;
        BMRBo:atom_chem_shift.atom_type "C" ;
        BMRBo:atom_chem_shift.entry_id ?entry_id ;
        BMRBo:atom_chem_shift.seq_id ?seq_id ;
        BMRBo:atom_chem_shift.comp_id ?comp_id ;
        BMRBo:atom_chem_shift.val ?ca_ppm .

} ORDER BY ?entry_id
LIMIT 100
