PREFIX BMRBo: <https://bmrbpub.pdbj.org/schema/mmcif_nmr-star.owl#>

SELECT ?year (COUNT(?year) AS ?count)
FROM <https://bmrbpub.pdbj.org/rdf/bmr>
WHERE {

  ?s_cit BMRBo:citation.id "1" ;
         BMRBo:citation.year ?year .

} GROUP BY ?year ORDER BY ?year
