PREFIX BMRBo: <https://bmrbpub.pdbj.org/schema/mmcif_nmr-star.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?entry_id ?entity_id ?entity_label ?species ?tax_id ?link_to_taxonomy
FROM <https://bmrbpub.pdbj.org/rdf/bmr>
WHERE {

  ?s_src BMRBo:entity_experimental_src.entry_id ?entry_id ;
         BMRBo:entity_experimental_src.entity_id ?entity_id ;
         BMRBo:entity_experimental_src.entity_label ?entity_label ;
         BMRBo:entity_experimental_src.host_org_scientific_name ?species ;
         BMRBo:entity_experimental_src.host_org_ncbi_taxonomy_id ?tax_id ;
         rdfs:seeAlso ?link_to_taxonomy .

  ?link_to_taxonomy rdfs:label ?label .

  FILTER (STRSTARTS(?label, \"info:taxonomy\"))

} ORDER BY ?entry_id
LIMIT 100
