PREFIX BMRBo: <https://bmrbpub.pdbj.org/schema/mmcif_nmr-star.owl#>

SELECT ?entry_id ?axis ?offset
FROM <https://bmrbpub.pdbj.org/rdf/bmr>
WHERE {

  ?s_lacs BMRBo:lacs_plot.entry_id ?entry_id ;
          BMRBo:lacs_plot.y_coord_name ?axis ;
          BMRBo:lacs_plot.y_axis_chem_shift_offset ?offset .

} ORDER BY ?entry_id
