PREFIX BMRBo: <https://bmrbpub.pdbj.org/schema/mmcif_nmr-star.owl#>

SELECT ?entry_id ?software_id ?name ?version ?submission_date ?task
FROM <https://bmrbpub.pdbj.org/rdf/bmr>
WHERE {

  ?s_soft BMRBo:software.entry_id ?entry_id ;
          BMRBo:software.id ?software_id ;
          BMRBo:software.name ?name ;
          BMRBo:software.version ?version .

  ?s_task BMRBo:task.entry_id ?entry_id ;
          BMRBo:task.software_id ?software_id ;
          BMRBo:task.task ?task .

  ?s_ent  BMRBo:entry.id ?entry_id ;
          BMRBo:entry.submission_date ?submission_date .

} ORDER BY ?entry_id
LIMIT 100
